[profile.default]
src = 'contracts'
test = 'test'
out = 'out'
libs = ['lib']
remappings = [
    '@juicebox=contracts/',
    '@chainlink/=node_modules/@chainlink/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@paulrberg/=node_modules/@paulrberg/',
    '@rari-capital/=node_modules/@rari-capital/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    '@ensdomains/=node_modules/@ensdomains/'
]
libraries = []
cache = true
force = false
evm_version = 'london'
gas_reports = ['*']
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = []
fuzz_runs = 1024
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 14126430
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1643802347
block_difficulty = 0
