[profile.default]
src = 'contracts'
test = 'forge_tests'
out = 'out'
libs = ['lib']
remappings = [
    '@juicebox=contracts/',
    '@chainlink/=node_modules/@chainlink/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@paulrberg/=node_modules/@paulrberg/',
    '@rari-capital/=node_modules/@rari-capital/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'prb-math/=node_modules/prb-math/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    '@ensdomains/=node_modules/@ensdomains/'
]
libraries = []
gas_reports = ['*']
verbosity = 3
ignored_error_codes = []
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 14126430
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1643802347
block_difficulty = 0
sizes=true
match_contract = "_Local" # Do not run fork tests

[profile.CI] # run via FOUNDRY_PROFILE=CI foundry test
fs_permissions = [{ access = "read", path = "./deployments/mainnet"}] # Get the deployment addresses for forking
match_contract = "_Fork"
